### ISSUE TITLE
[POST/email/addEcoNews] Incorrect behavior of AddEcoNews end-point. Response 200 OK always.

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#207]
**Environment:** 116.0.3 (64-bit).
**Reproducible:** always.

**Preconditions**
Moved to Swagger http://localhost:8065/swagger-ui.html#/
Sign-in on Swagger as user.

**Steps to reproduce**
1. Click on Email controller
2. Click on POST/email/addEcoNews
3. Click on 'Try out'
4. Enter data {
  "author": {
    "email": "Test3421gmail.com",
    "id": 154,
    "name": "Test1526435"
  },
  "creationDate": "2023-08-23T11:46:06.482Z",
  "imagePath": "string",
  "source": "string",
  "text": "Test1241254125125125124",
  "title": "Test1111",
  "unsubscribeToken": "string"
}

**Actual result**
Response 200 OK

**Expected result**
Response 400 Bad request

**User story and test case links**
E.g.: "User story #23

**Comment by nataliiapovzhyk** [comment]
after fix for other bug - this issue is not valid any more.
there is valid response code:



![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/a3e1fa56-0f41-4d90-8ddf-a002a34e879b)

**Comment by nataliiapovzhyk** [comment]
fixed: 


![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/70892169-bd07-4f63-9bef-845f92fb2cf0)

**Comment by nataliiapovzhyk** [comment]
fix https://github.com/GreenCityProject/GreenCityUser21_team_1_May/pull/28/files
