### ISSUE TITLE
[POST/email/sendHabitNotification] Incorrect behavior of sendHabitNotification end-point. Need 401 unauthorized.

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#214]
**Environment**: Firefox 116.0.3 (64-bit).
**Reproducible**: always.

**Preconditions**
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on Email controller
2. Click on POST/email/sendHabitNotification
3. Click on 'Try out'
4. Enter valid data {
    "email": "Test1@gmail.com",
    "name": "Test1"
    }

**Actual result**
Response 200 OK

**Expected result**
Response 401 unauthorized

**User story and test case links**

**Comment by tellmant** [comment]
## Changes:
**No changes required.**

> **NOTES:** Behavior of /email/sendHabitNotification endpoint is correct

## Results:
![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/128901331/b618b6a8-369c-4392-a74e-11d9bf8f803d)
> *Without authentication*
