### ISSUE TITLE
[GET /user/emailNotifications] In Get all available email notifications statuses 200 OK different response

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#248]
**Environment**: Firefox 116.0.3 (64-bit).
**Reproducible**: always.

**Preconditions**
Sign-in us User
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on GET /user/emailNotifications
3. Click on 'Try out'
4. Click on Execute

**Actual result**
[
  "DISABLED",
  "IMMEDIATELY",
  "DAILY",
  "WEEKLY",
  "MONTHLY"
]
![image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/39855858/63352e3c-2674-4d6f-9d7c-79baa017c6ad)

**Expected result**
Align documentation with the real answer
200 OK
[
  "DISABLED",
  "IMMEDIATELY",
  "DAILY",
  "WEEKLY",
  "MONTHLY"
]

User story and test case links

**Comment by tellmant** [comment]
## Changes:
**No changes required.**

> **NOTES:** Behavior of /user/emailNotifications endpoint is correct

## Results:
![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/128901331/7912ca7b-ef9d-497b-b6ef-11e5e7702859)
> *With authenticated USER role*
