### ISSUE TITLE
[POST /user/search] In /user/search response 500 Internal Server Error

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#291]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in as Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on POST /user/search
3. Click on 'Try out'
4. Enter valid data 

**Actual result**
Response 500 Internal Server Error

**Expected result**
Response 200 OK

**Comment by ushh789** [comment]
I think this bug was also fixed. Please check: https://github.com/OlhenShu/ProjectStage_Team1_May/issues/292#issuecomment-2130308366.
Here I've tried to execute with valid request body:
```
{
  "pageable": {
    "page": 0,
    "size": 1,
    "sort": [
      "string"
    ]
  },
  "userViewDto": {
    "id": 3,
    "name": "Test",
    "email": "test@mail.com",
    "userCredo": "test",
    "role": "ROLE_ADMIN",
    "userStatus": 2
  }
}
```
The response body looks fine... Please review and give feedback, so I can close this issue.

**Comment by tellmant** [comment]
No changes are required, issue seem to be resolved.
