### ISSUE TITLE
[GET /user/lang] In /user/lang incorrect response 403 Forbidden - need 401 Unauthorized

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#293]
**Environment**: Firefox 116.0.3 (64-bit).
**Reproducible**: always.

**Preconditions**
Sign-in as Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on GET /user/lang

**Actual result**
Contain 403 Forbidden - Incorrect
![image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/39855858/0ab9c533-bff3-475b-8f5b-87c136345f6f)

**Expected result**
Need 401 Unauthorized (Need only these responses - 200 OK, 400 Bad request, 401 Unauthorized)

**Comment by nataliiapovzhyk** [comment]
this bug is not reproducible



![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/28bfb632-1b47-4b19-911f-d0549c150f38)

**Comment by nataliiapovzhyk** [comment]
with correct request data - response code is 200.


![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/fb4ae961-033f-45f9-85e5-a11c0dc15635)

**Comment by nataliiapovzhyk** [comment]
admin should not have access here. to update
