### ISSUE TITLE
[PATCH /user/status] In /user/status response 401 Unauthorized - always

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#312]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/status
3. Click on 'Try out'
4. Enter valid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 200 OK

**Comment by IliaWithHat** [comment]
Already fixed by my pull request https://github.com/GreenCityProject/GreenCityUser21_team_1_May/pull/15
