### ISSUE TITLE
[PATCH /user/status] In /user/status response 401 Unauthorized - need 400 Bad request

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#313]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/status
3. Click on 'Try out'
4. Enter invalid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 400 Bad request

**Comment by IliaWithHat** [comment]
Bug not found

**Comment by IliaWithHat** [comment]
Maybe fixed by this pull request https://github.com/GreenCityProject/GreenCityUser21_team_1_May/pull/15
