### ISSUE TITLE
[PATCH /user/status] In /user/status response 401 Unauthorized - need 403 Forbidden

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#314]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us user
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/status
3. Click on 'Try out'
4. Enter valid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 403 Forbidden

**Comment by nataliiapovzhyk** [comment]
issue was reproduced


![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/7a1484ef-5573-4a96-b876-d129acce704b)

**Comment by nataliiapovzhyk** [comment]
fix https://github.com/GreenCityProject/GreenCityUser21_team_1_May/pull/18



![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/45eed268-bf8d-4203-ae93-819a910a60f5)
