### ISSUE TITLE
[PUT /user/updateUserLastActivityTime/{date}] In /user/updateUserLastActivityTime/{date} response 401 Unauthorized - Always

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#315]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PUT /user/updateUserLastActivityTime/{date}
3. Click on 'Try out'
4. Enter valid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 200 OK

**Comment by nataliiapovzhyk** [comment]
https://github.com/GreenCityProject/GreenCityUser21_team_1_May/pull/32/files. added test

**Comment by nataliiapovzhyk** [comment]
fixed already by other bug fix

verified 

![Image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/144839063/588ac2b5-009f-4dd8-974c-2b705a9e69c4)
