### ISSUE TITLE
See an advertising info of application

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team1_May#75]
**As** a user **I want to** see short information about application, **so that I** can understand what the app is about and whether I want to track a habit.

**Mockups:**
![image](https://github.com/OlhenShu/ProjectStage_Team1_May/assets/39855858/93832933-2f9c-4ead-894f-59e8e61135c0)

**Acceptance criteria:**

1. User can see Advertising info of application on the Home page.

2. Advertising info section contain:
         2.1. Title
         2.2. Text
         2.3. Picture 
         2.4. Button "Start forming a habit"

3. WHEN user clicks on "Start forming a habit" button, system shall: 
         3.1. navigate logged in user to Personal cabinet
         3.2. display log in form for unlogged user.

**Comment by IliaWithHat** [comment]
Already done on front side.
